In [196]:
import igl
import meshplot as mp
import numpy as np

# Hello world

In [197]:
v, f = igl.read_triangle_mesh("data/bunny.obj")
mp.plot(v, f, v[:, 0])

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0002189…

# Data Representation
Meshes are represented by a numpy array of vertex coordinates (nx3) and a numpy array of face indices (mx3) and can be loaded from 3D file formats

In [198]:
v: np.array # Array of vertex coordinates (nx3)
f: np.array # Array of face indices (mx3)
v, f = igl.read_triangle_mesh("data/bunny.obj")
print(v)
print(f)

[[ 0.579785 -0.556431  0.335583]
 [ 0.566629 -0.530296  0.334038]
 [ 0.533192 -0.543823  0.342491]
 ...
 [-0.521482  0.641195 -0.549294]
 [-0.555727  0.655425 -0.519703]
 [-0.534968  0.676574 -0.551021]]
[[   0    1    2]
 [   0    3    1]
 [   1    4    2]
 ...
 [3296 3298 3300]
 [3299 3300 3298]
 [3299 3295 3300]]


# Visualizing Surfaces and Pointclouds

In [199]:
mp.plot(v, f, c=v[:, 0])
mp.plot(v, c=v[:, 0],shading={"point_size":0.3})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0002189…

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0002189…

# Gauss map of the input mesh

In [200]:
# Loading the mesh
v, f = igl.read_triangle_mesh("data/sphere.obj")
# v, f = igl.read_triangle_mesh("data/cylinder.obj")
# v, f = igl.read_triangle_mesh("data/bunny.obj")
mp.plot(v,f,c=v[:,0])

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

In [201]:
# Calculating per face normals
nf = igl.per_face_normals(v, f, np.array([0.0, 0.0, 0.0]))
# Plotting face normals
mp.plot(v,f,c=nf)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

In [202]:
# Calculating per vertex normals
nv = igl.per_vertex_normals(v, f)
avg = igl.avg_edge_length(v, f)
# Plotting vertex normals as lines
pv=mp.plot(v,f, c=nv)
pv.add_lines(v, v + nv*avg)

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

1

In [203]:
# Calculating the principal curvature, mean curvature and gassian curvature.
v1, v2, k1, k2 = igl.principal_curvature(v, f)
mean_curv = 0.5 * (k1 + k2)
gaussian_curv=k1*k2
avg = igl.avg_edge_length(v, f)

# Plotting gaussian curvature + directions
pgc=mp.plot(v, f, c=gaussian_curv)
pgc.add_lines(v + v1 * avg/3, v - v1 * avg/3, shading={"line_color": "red"})
pgc.add_lines(v + v2 * avg/3, v - v2 * avg/3, shading={"line_color": "green"})



Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

2

In [204]:
# Plotting the gauss map
vs, fs = igl.read_triangle_mesh("data/unit_sphere.obj")
vs=vs*0.95
pgm=mp.plot(vs, fs,shading={"flat":False})
pgm.add_points(nf,shading={"point_size":0.2})
ev, fe, ef = igl.edge_topology(v, f)
ef = ef[np.all(ef != -1, axis=1)]
pgm.add_lines(nf[ef[:,0]],nf[ef[:,1]],shading={"line_color": "red"})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(4.7683715…

2

# How to calculate the developabi

In [205]:
vf,ni=igl.vertex_triangle_adjacency(f,v.shape[0])

In [206]:
developability=np.zeros(v.shape[0])
for i in range(0,v.shape[0]):
    dmat=nf[vf[ni[i]:ni[i+1]]]
    developability[i]=min(np.linalg.eigvals(np.dot(dmat.T,dmat)))
pd=mp.plot(v,f, c=developability,shading={"point_size":0.3})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…