In [18]:
import autograd.numpy as jnp  # Thinly-wrapped numpy
from autograd import grad, jacobian    # The only autograd function you may ever need

In [19]:
import drawSvg as draw
from drawSvg.widgets import DrawingWidget
import hyperbolic.poincare.shapes as hyper  # pip3 install hyperbolicd
import numpy as np


canvas_size=(800,800)
# Create drawing
d = draw.Drawing(*canvas_size, origin='center')

linkage = draw.Group()
d.append(linkage)
traj=draw.Group()
d.append(traj)


def redraw_linkage(nodes=[], edges=[],node_radius=6,edge_width=5):
    linkage.children.clear()
    for id1,id2 in edges:
        linkage.draw(draw.Line(*nodes[id1],*nodes[id2],stroke='gray',stroke_width=edge_width))
    for x,y in nodes[1:-1]:
        linkage.draw(draw.Circle(x,y,node_radius,fill='green'))
    x,y=nodes[0]
    linkage.draw(draw.Circle(x,y,node_radius,fill='blue'))
    x,y=nodes[-1]
    linkage.draw(draw.Circle(x,y,node_radius,fill='orange'))

def redraw_trajectory(drive_node=[],end_node=[]):
    traj.children.clear()
    for p0,p1 in zip(drive_node[:-1],drive_node[1:]):
        traj.draw(draw.Line(*p0,*p1,stroke='blue',stroke_width=3))
    for p0,p1 in zip(end_node[:-1],end_node[1:]):
        traj.draw(draw.Line(*p0,*p1,stroke='orange',stroke_width=3))
        
        
def rotation_matrix(theta=0):
    c, s = jnp.cos(theta), jnp.sin(theta)
    R = jnp.array(((c, -s), (s, c)))
    return R

def simulate_linkage(nodes=[],edges=[],lengths=[]):
    for i in range(0,len(edges),2):
        e02,e12 = edges[[i,i+1],:]
        l02,l12 = lengths[[i,i+1]]
        p0, p1 = nodes[[e02[0],e12[0]],:]
        
        if np.linalg.norm(p1-p0) > l02 + l12:
            p0 = p1 - (l02+l12)*(p1-p0) / np.linalg.norm(p1 - p0)
            nodes[e02[0],:] = p0
        
        p2 = simulate_linkage_impl(p0,p1,l12,l02)
        print(p2)
        print(jacobian(simulate_linkage_impl)(p0,p1,l12,l02))
        nodes[e02[1],:] = p2
        
def simulate_linkage_impl(p1, p0, l12, l02):
    v01 = (p1-p0) / jnp.linalg.norm(p1 - p0)
    l01 = jnp.linalg.norm(p1 - p0)
    phi = jnp.arccos(max(-1,min(1,(l01**2+l02**2-l12**2)/(2*l01*l02))))
    return jnp.dot(rotation_matrix(phi), v01*l02+p0)


In [20]:
nodes=np.array([(100,100),(0,0),(0,0),(0,0),(0,0),(0,0),(0,0)])
edges=np.array([(0,2),(1,2),(2,3),(1,3),(1,4),(0,4),(3,5),(4,5),(5,6),(4,6)])
lengths=np.array([100,100,100,100,100,150,100,100,150,100])
drive_node=[]
end_node=[]
# Create interactive widget and register mouse events
widget = DrawingWidget(d)
@widget.mousedown
def mousedown(widget, x, y, info):
    drive_node.append([*nodes[0]])
    if len(drive_node)>1:
        for i in range(0,10):
            nodes[0,:]=(1-i/10.0)*np.asarray(drive_node[-2])+(i/10.0)*np.asarray(drive_node[-1])
            simulate_linkage(nodes,edges,lengths)
            end_node.append([*nodes[-1]])
        nodes[0,:]=drive_node[-1]
    else:
        end_node.append([*nodes[-1]])
    redraw_trajectory(drive_node,end_node)
    redraw_linkage(nodes,edges)
    widget.refresh()
@widget.mousemove
def mousemove(widget, x, y, info):
    nodes[0]=(x,y)
    simulate_linkage(nodes,edges,lengths)
    redraw_trajectory(drive_node,end_node)
    redraw_linkage(nodes,edges)
    widget.refresh()

widget

DrawingWidget()

[97.54127037 22.03861555]
[[  5100439.66312687   1152400.48037175]
 [-22574165.92569112  -5100438.66312687]]
[29.31055466 95.608009  ]
[[ 0.7499762  -0.81555188]
 [-0.22992026  0.2500238 ]]
[50.95459606 85.93098333]
[[-0.66234661 -0.59055446]
 [ 0.39275244  0.35018177]]
[-131.81000466  -25.12744216]
[[-1.45091996 -3.34115306]
 [ 0.38429877  2.35041133]]
[-73.63340818 -27.22699947]
[[ 0.43770331 -0.42719301]
 [-0.55327644  0.11791897]]
[-96.09411193 -27.67528955]
[[-0.18762434 -0.3420381 ]
 [ 0.65146906  1.18762434]]
[-24.53126177 -96.9444026 ]
[[ 0.80150842 -0.78441328]
 [-0.20281741  0.19849158]]
[10.12552593 20.83207994]
[[-0.68944188 -1.01192239]
 [ 0.33510632  0.49184942]]
[ 49.56213874 -60.35345357]
[[0.74487539 0.17639045]
 [0.55945871 0.16016073]]
[131.89886471 -39.03892678]
[[0.66500853 0.19428661]
 [1.55790837 0.32057665]]
[-96.85138517  24.89596735]
[[0.03099046 0.12056045]
 [0.12056045 0.46900954]]
[-69.07689005 -72.30756019]
[[ 0.22638218 -0.8097993 ]
 [-0.21626752  0.77361

 [ 0.15657266  1.00776402]]
[-99.97014733   2.44328508]
[[0.00547389 0.02430636]
 [0.2239711  0.99452611]]
[-51.25486502 -85.86581864]
[[ 0.47652767 -0.87695832]
 [-0.28444801  0.52347233]]
[-23.26856548 -13.34285128]
[[-0.38293883 -0.14680411]
 [ 0.66780608  0.25601133]]
[ 75.07398259 -95.66797837]
[[1.02560729 0.15757533]
 [1.01573381 0.04163654]]
[141.23307072 -21.49590771]
[[-0.03682478 -0.00429599]
 [ 0.62468909  1.00751051]]
[-99.89572582   4.56551889]
[[0.01567085 0.04498664]
 [0.34288558 0.98432915]]
[-53.00688724 -84.79545922]
[[ 0.45313207 -0.87482816]
 [-0.28325951  0.54686793]]
[-16.95764652  -9.70982085]
[[-0.39540507 -0.15738679]
 [ 0.69055232  0.27486703]]
[ 64.44883246 -95.98622893]
[[ 1.06684428  0.06282408]
 [ 0.83213998 -0.0149553 ]]
[143.40020731 -31.32069302]
[[0.07694908 0.09170356]
 [0.88505303 0.91543739]]
[-99.93231367   3.67867964]
[[0.01397584 0.03629724]
 [0.3796574  0.98602416]]
[-52.13140873 -85.33648823]
[[ 0.4648155  -0.87607005]
 [-0.28395224  0.5351845

[-71.91345127  69.48708892]
[[ 1.52283309 -0.50519268]
 [ 1.57600764 -0.52283309]]
[-96.05511544 -27.81033618]
[[-0.08100022 -0.31297635]
 [ 0.27976956  1.08100022]]
[28.78026794 47.5500079 ]
[[-1.64769402  0.99728849]
 [ 0.99728849 -0.60362198]]
[-38.84613325 -43.10553184]
[[ 0.60964859 -0.4136995 ]
 [-0.3352648   0.01398725]]
[  4.06050036 -95.59679451]
[[ 1.07772413 -0.79242483]
 [ 0.10489814 -0.07701424]]
[-93.97616902  34.18303169]
[[ 1.06386411 -0.02323003]
 [ 2.92478076 -0.06386411]]
[-76.33270539 -64.60122357]
[[ 0.12515394 -0.74039202]
 [-0.1478817   0.87484606]]
[12.42885351 66.28721869]
[[-2.96716132  0.55634275]
 [ 0.55634275 -0.10431427]]
[-24.164949   -40.49260203]
[[ 0.70927466 -0.08553183]
 [-0.07075566 -0.1875866 ]]
[ 23.67834865 -80.82934871]
[[ 1.1677772  -0.39551371]
 [ 0.49688996 -0.16843581]]
[-96.86661069  24.83666107]
[[0.83219133 0.04302625]
 [3.24566789 0.16780867]]
[-69.07689005 -72.30756019]
[[ 0.22638218 -0.8097993 ]
 [-0.21626752  0.77361782]]
[ 6.9503719 

[56.17136069 82.73317495]
[[-0.46855682 -2.16299493]
 [ 0.31812479  1.46855682]]
[-43.68314039  89.95433978]
[[ 1.04031233 -0.08301301]
 [ 0.50519085 -0.04031233]]
[ 56.914503   -24.39192986]
[[-0.40750272 -0.95083969]
 [-0.95083969 -2.21862593]]
[-41.24337473  31.93849942]
[[-0.09433025  0.23898417]
 [ 0.29055448  0.66988614]]
[-88.84109444 -12.39847845]
[[-0.14113933 -0.24825132]
 [ 0.65043141  1.14234411]]
[95.98310217 28.05787051]
[[-0.96958138 -0.57574988]
 [ 3.31683862  1.96958138]]
[22.93852651 97.33357078]
[[ 0.8151634  -0.78430522]
 [-0.19210892  0.1848366 ]]
[ 29.87261114 -68.70700563]
[[-3.35335633 -1.45798101]
 [-1.45798101 -0.63390479]]
[ 2.44767949 40.31614624]
[[ 0.46949012  0.37762154]
 [ 0.36302006 -0.00631611]]
[-57.18135414  52.86138286]
[[0.73443538 0.18125658]
 [1.0823389  0.26804023]]
[99.70366114 -7.69285096]
[[0.26134018 0.05699289]
 [3.38711522 0.73865982]]
[55.6234135  83.10256236]
[[ 0.4183483  -0.869     ]
 [-0.28001496  0.5816517 ]]
[  4.88020916 -70.763032

[-42.46741279 -90.53462791]
[[ 0.64906953 -0.74813505]
 [-0.30446144  0.35093047]]
[ 57.65544375 -81.70587375]
[[0.94452828 0.07861123]
 [0.66650284 0.05547172]]
[ 1.4934584 -8.9124277]
[[ 0.03385129 -0.90849197]
 [ 0.00567247 -0.15223629]]
[106.01242291  14.75087641]
[[-0.10072928 -0.18196342]
 [ 0.48564227  1.12495127]]
[ 95.10902846 115.41545329]
[[ 0.18207108 -1.1115416 ]
 [-0.13007528  0.82070228]]
[-32.88261929 -94.43904568]
[[ 0.65483463 -0.99131664]
 [-0.22800609  0.34516537]]
[ 66.17335606 -74.97390845]
[[0.85393282 0.16549301]
 [0.75369687 0.14606718]]
[-4.28873654 10.47089742]
[[ 0.26878265 -1.0179774 ]
 [ 0.1100897  -0.41694964]]
[88.76444344 13.72164353]
[[-0.02906956 -0.1308842 ]
 [ 0.35849863  0.98872285]]
[101.13924486 106.23212675]
[[-0.22272955 -1.1076905 ]
 [ 0.20698972  1.20981937]]
[-26.4679632 -96.43364  ]
[[ 0.66913249 -1.20548597]
 [-0.18365556  0.33086751]]
[ 70.74138457 -70.67995832]
[[0.79242026 0.20739949]
 [0.79310894 0.20757974]]
[-13.52552337  20.38249845

[-38.5581561  -92.26737559]
[[ 0.74548598 -0.60903691]
 [-0.31153552  0.25451402]]
[ 61.16602675 -79.11205453]
[[0.90869271 0.11809672]
 [0.702562   0.09130729]]
[  3.30634827 -19.28873849]
[[ 0.02405855 -0.84366187]
 [ 0.00412396 -0.14461495]]
[112.85975019  27.961507  ]
[[-0.17880161 -0.38680766]
 [ 0.38125435  1.23216746]]
[ 79.24871055 123.29880423]
[[ 0.50613667 -1.02940315]
 [-0.25066216  0.48474601]]
[-39.78810394 -91.74370161]
[[ 0.73076592 -0.62080191]
 [-0.3169241   0.26923408]]
[ 60.36254355 -79.72680438]
[[0.92089606 0.10448043]
 [0.69722634 0.07910394]]
[  3.0032969  -18.86320965]
[[ 0.01473116 -0.84791719]
 [ 0.00234541 -0.13500073]]
[112.50440071  26.75390321]
[[-0.17553943 -0.36550284]
 [ 0.40786159  1.22834745]]
[ 80.65177726 123.05087859]
[[ 0.4827388  -1.03896102]
 [-0.24724994  0.50965827]]
[-41.67546914 -90.90189917]
[[ 0.70787421 -0.63718033]
 [-0.32453656  0.29212579]]
[ 58.59716698 -81.03315385]
[[0.93887559 0.08452804]
 [0.6789252  0.06112441]]
[  2.56286138 -1

[-40.77301931 -91.3102453 ]
[[ 0.78488564 -0.48174369]
 [-0.35047718  0.21511436]]
[ 59.43853407 -80.41803695]
[[0.92708051 0.09865724]
 [0.68522323 0.07291949]]
[  3.6110913  -31.69262525]
[[-0.04201088 -0.80155198]
 [-0.00478676 -0.09132968]]
[119.01379391  36.60589359]
[[-0.25297437 -0.5885576 ]
 [ 0.30622864  1.32353384]]
[ 71.93778164 120.09526982]
[[ 0.68990039 -0.8223997 ]
 [-0.2810745   0.26377346]]
[-40.77301931 -91.3102453 ]
[[ 0.78488564 -0.48174369]
 [-0.35047718  0.21511436]]
[ 59.43853407 -80.41803695]
[[0.92708051 0.09865724]
 [0.68522323 0.07291949]]
[  3.6110913  -31.69262525]
[[-0.04201088 -0.80155198]
 [-0.00478676 -0.09132968]]
[119.01379391  36.60589359]
[[-0.25297437 -0.5885576 ]
 [ 0.30622864  1.32353384]]
[ 71.93778164 120.09526982]
[[ 0.68990039 -0.8223997 ]
 [-0.2810745   0.26377346]]
[-38.22461059 -92.40605578]
[[ 0.80133978 -0.48025101]
 [-0.33148153  0.19866022]]
[ 61.16602675 -79.11205453]
[[0.90869271 0.11809672]
 [0.702562   0.09130729]]
[  4.39066573 -3

[ -3.69499287 -99.93171182]
[[ 0.9080648  -2.48640324]
 [-0.03357586  0.0919352 ]]
[ 85.33648823 -52.13140873]
[[0.5351845  0.28395224]
 [0.87607005 0.4648155 ]]
[-60.77629653  -9.59625735]
[[-0.06322807  0.40044445]
 [ 0.40044445 -2.53614815]]
[51.62005741 -4.83293649]
[[-0.11291837 -0.25087825]
 [-0.20690812  0.68965917]]
[68.47009286 58.22011443]
[[ 0.03886702 -0.94354191]
 [-0.03914567  0.96393448]]
[-29.28586986 -95.61557314]
[[ 0.57072459 -1.40154327]
 [-0.1748059   0.42927541]]
[ 68.51402014 -72.84112194]
[[0.82390044 0.18722138]
 [0.77495692 0.17609956]]
[-20.80926052  25.5254494 ]
[[ 0.65204857 -1.12763241]
 [ 0.53157335 -0.91928632]]
[67.9830162   3.53648797]
[[ 0.00282428 -0.02902823]
 [ 0.26314889  0.84600626]]
[103.35686852  72.01931311]
[[-0.37888605 -0.66109629]
 [ 0.65375856  1.38379248]]
[-32.67766468 -94.51015941]
[[ 0.56032252 -1.27163277]
 [-0.19373612  0.43967748]]
[ 66.17335606 -74.97390845]
[[0.85393282 0.16549301]
 [0.75369687 0.14606718]]
[-14.15643682  22.9188

[[-2.2868884   0.91475536]
 [ 0.91475536 -0.36590214]]
[30.88715633 41.20433598]
[[ 0.67761306 -0.26659245]
 [-0.22299815 -0.10723855]]
[-13.9176806   88.09477603]
[[ 1.15051136 -0.62572509]
 [ 0.27430771 -0.14890458]]
[ 62.25667228 -78.25667228]
[[ 2.72398806 -2.16705396]
 [ 2.16705396 -1.72398806]]
[98.87578715 14.95254876]
[[-0.0638226  -0.16087719]
 [ 0.42203572  1.0638226 ]]
[-54.71067812 -54.71067812]
[[-2.20970869  2.20970869]
 [ 2.20970869 -2.20970869]]
[38.33148011  9.69056571]
[[ 0.28722606 -0.4278237 ]
 [-0.44676176  0.15132234]]
[31.49807436 69.42889309]
[[ 0.73663072 -1.0790257 ]
 [-0.18043858  0.26499973]]
[ 15.14015479 -98.84723422]
[[ 1.62049607 -4.05110263]
 [ 0.24820686 -0.62049607]]
[ 93.34920246 -35.85981595]
[[0.32630454 0.25879809]
 [0.84942623 0.67369546]]
[-74.47638212 -20.31174058]
[[-0.30359701  1.11318902]
 [ 1.11318902 -4.08169309]]
[ 37.24015009 -10.31281797]
[[-0.1191798  -0.26949222]
 [-0.29305865  0.55552388]]
[60.55700578 45.38759964]
[[ 0.0868225  -0.9

[-30.99366261 -95.07572181]
[[ 0.43136539 -1.7443355 ]
 [-0.14062048  0.56863461]]
[ 67.68584518 -73.61131953]
[[0.83241167 0.18225964]
 [0.76540521 0.16758833]]
[-37.82996507  24.30274508]
[[ 1.18606022 -1.02585241]
 [ 1.84623656 -1.59685504]]
[56.77287066 -6.03135896]
[[-0.04536113  0.01424784]
 [ 0.18416257  0.78936192]]
[94.07344245 53.11122059]
[[-0.26576462 -0.55345368]
 [ 0.57261497  1.29612997]]
[-34.51130515 -93.8561123 ]
[[ 0.44698379 -1.50396952]
 [-0.16435791  0.55301621]]
[ 64.60122357 -76.33270539]
[[0.87484606 0.1478817 ]
 [0.74039202 0.12515394]]
[-24.12898373  28.00793703]
[[ 0.74980722 -1.22637665]
 [ 0.64596283 -1.05652988]]
[63.0414759  -3.20723542]
[[0.01223956 0.03904942]
 [0.28161886 0.80228058]]
[103.5797402   59.40934515]
[[-0.32880738 -0.50103819]
 [ 0.74137598  1.34532869]]
[-31.55389025 -94.89126414]
[[ 0.56349638 -1.31268697]
 [-0.18737766  0.43650362]]
[ 67.02325415 -74.21511573]
[[0.84582377 0.17071995]
 [0.76385869 0.15417623]]
[-16.19480604  23.98036392

[ 26.74802845 119.96346497]
[[ 0.44826028 -1.50551221]
 [-0.22209068  0.56292388]]
[ 60.09749752 -79.92678394]
[[ 1.32367691 -0.43047473]
 [ 0.99528175 -0.32367691]]
[99.14900707 13.01823322]
[[-0.05916634 -0.13906821]
 [ 0.45062059  1.05916634]]
[-38.92506397  -8.22095013]
[[-0.43641042 -0.0205716 ]
 [ 2.06634309  0.09740369]]
[37.01019286 48.82175686]
[[ 0.42407018 -0.53179482]
 [-0.31665959  0.37172901]]
[  8.8346938  115.58312808]
[[ 0.73449492 -1.40442057]
 [-0.19156014  0.288712  ]]
[ 64.60121259 -76.33271469]
[[ 1.35074576 -0.41444077]
 [ 1.14315094 -0.35074576]]
[98.38442144 17.90267069]
[[-0.07138744 -0.19495664]
 [ 0.39231086  1.07138744]]
[-40.35846197 -16.75243084]
[[-0.97557982 -0.24241144]
 [ 2.35027989  0.58399601]]
[35.50722963 45.50133216]
[[ 0.45335957 -0.50783913]
 [-0.33123731  0.30201834]]
[  5.7960039  109.47201889]
[[ 0.81963853 -1.30447348]
 [-0.15810574  0.21010223]]
[ 67.87014819 -73.44142554]
[[ 1.37771598 -0.40872166]
 [ 1.27320224 -0.37771598]]
[97.49637255

 [-0.35302777  0.26286396]]
[  7.08212721 104.68199844]
[[ 0.85695159 -1.203914  ]
 [-0.13343851  0.17084335]]
[ 60.41553809 -79.68665357]
[[ 1.40772533 -0.53777998]
 [ 1.06728642 -0.40772533]]
[99.14900707 13.01823322]
[[-0.05916634 -0.13906821]
 [ 0.45062059  1.05916634]]
[-41.54441729 -17.29339158]
[[-1.08312575 -0.27962952]
 [ 2.60202448  0.67176212]]
[37.8884984  42.47449813]
[[ 0.41927494 -0.50495064]
 [-0.3463323   0.32128899]]
[ 10.69480207 107.09447195]
[[ 0.77360191 -1.29821146]
 [-0.1738081   0.25729088]]
[ 37.78799039 -92.58546205]
[[ 1.36219846 -0.88743306]
 [ 0.55597003 -0.36219846]]
[ 99.07139328 -13.59628748]
[[0.09800151 0.12378781]
 [0.71410271 0.90199849]]
[-40.31158513   1.35240251]
[[ 0.07129627 -0.01399409]
 [ 2.12515564 -0.41712733]]
[48.01489594 36.27394045]
[[ 0.20612586 -0.48262556]
 [-0.27880288  0.57967181]]
[ 38.13241851 107.73742166]
[[ 0.31913888 -1.3864899 ]
 [-0.19832048  0.70536401]]
[ 34.94907428 -93.6939817 ]
[[ 1.22129368 -0.59325996]
 [ 0.45555843 

[ 12.08673747 142.34471126]
[[ 0.72792476 -1.51404879]
 [-0.16591601  0.2564108 ]]
[ 43.13596858 -90.21800383]
[[ 1.10330517 -0.21606067]
 [ 0.52752372 -0.10330517]]
[99.70819497 -7.6338624 ]
[[0.0500727  0.07272837]
 [0.65401468 0.9499273 ]]
[-9.34600586  4.05828524]
[[ 0.38329203 -0.2293816 ]
 [ 0.88270028 -0.52825311]]
[54.26555634 72.66671653]
[[ 0.35752724 -0.75914015]
 [-0.26305166  0.60559011]]
[ -3.81969912 147.06359588]
[[ 0.95374373 -1.3498469 ]
 [-0.05045839  0.03463873]]
[ 47.90163787 -87.78059632]
[[ 1.08879454 -0.16271755]
 [ 0.59415228 -0.08879454]]
[99.97611914 -2.18531495]
[[0.01346907 0.02156396]
 [0.6161973  0.98653093]]
[-10.2844618    3.75770631]
[[ 0.34460429 -0.17965794]
 [ 0.94314706 -0.49170561]]
[50.3703679  74.47437746]
[[ 0.40974946 -0.76391778]
 [-0.27570046  0.54787882]]
[-10.85551326 145.74701705]
[[ 1.01770862 -1.29561494]
 [-0.00516351 -0.02807926]]
[ 65.97695359 -75.1468003 ]
[[ 1.01921495 -0.02188555]
 [ 0.89484446 -0.01921495]]
[98.10800179 19.360268

 [ 1.53736992  0.24867341]]
[20.7290212 65.2471995]
[[ 0.66941396 -0.50513755]
 [-0.22093439  0.18105207]]
[-33.67017424 121.97486101]
[[ 1.18764913 -1.1986085 ]
 [ 0.10745434 -0.18394179]]
[ 81.84620531 -57.45605866]
[[0.92670235 0.05145497]
 [1.3200883  0.07329765]]
[90.49676595 42.54803582]
[[-0.04695904 -0.49223914]
 [ 0.09987867  1.04695904]]
[-31.77760737 -13.37856006]
[[-0.66163061 -0.16003817]
 [ 1.57154713  0.38013286]]
[18.69184997 63.72169905]
[[ 0.6855694  -0.47784161]
 [-0.20595422  0.15084293]]
[-34.86971282 118.73026344]
[[ 1.20698664 -1.16276438]
 [ 0.13126056 -0.19757396]]
[ 83.73118203 -54.6725631 ]
[[0.89885832 0.06604081]
 [1.37660401 0.10114168]]
[88.88135562 45.82689846]
[[-0.03132828 -0.53174905]
 [ 0.06076126  1.03132828]]
[-32.18410215 -16.06035784]
[[-0.78283797 -0.2428187 ]
 [ 1.56876562  0.48659575]]
[16.7812502  61.99298398]
[[ 0.69821419 -0.44864618]
 [-0.19029457  0.12398602]]
[-36.04926728 115.44961323]
[[ 1.22482737 -1.12624375]
 [ 0.15532176 -0.2100821

[ 94.88893293 -31.56089998]
[[0.61434079 0.12827367]
 [1.84703674 0.38565921]]
[74.21511573 67.02325415]
[[ 0.15417623 -0.76385869]
 [-0.17071995  0.84582377]]
[-18.97875693 -43.99447091]
[[-1.96731376 -3.49325443]
 [ 0.84867868  1.50695361]]
[ 9.59740375 56.34208051]
[[ 0.79269744 -0.13612899]
 [-0.00420602 -0.08622748]]
[-51.43671923  90.3381239 ]
[[ 1.24173084 -0.42665089]
 [ 0.61254439 -0.2171613 ]]
[ 95.01563211 -31.17739012]
[[0.61868147 0.12512169]
 [1.88548211 0.38131853]]
[74.37186793 66.8492727 ]
[[ 0.1593048  -0.75566023]
 [-0.17723148  0.8406952 ]]
[-15.0456584  -46.54026583]
[[-2.17419905 -5.24427472]
 [ 0.70288073  1.6953828 ]]
[11.20457798 56.0916882 ]
[[ 0.79408979 -0.11841653]
 [ 0.00601828 -0.10717689]]
[-49.61854594  88.85427754]
[[ 1.21193146 -0.36781578]
 [ 0.62746244 -0.19282827]]
[ 94.495632   -32.71965056]
[[0.66370844 0.11644287]
 [1.91681596 0.33629156]]
[74.97390845 66.17335606]
[[ 0.14606718 -0.75369687]
 [-0.16549301  0.85393282]]
[ -8.80715169 -49.05593864

 [-0.25991957 -0.06016531]]
[-13.85138053  94.35966123]
[[ 1.13933637 -0.67115756]
 [ 0.23305712 -0.1369107 ]]
[ 63.95183682 -76.87758169]
[[ 1.49261151 -0.5921766 ]
 [ 1.24165258 -0.49261151]]
[98.45627024 17.50322401]
[[-0.07228557 -0.19062732]
 [ 0.40660894  1.07228557]]
[-29.69675715 -40.96104434]
[[-1.32668651  0.96184772]
 [ 0.96184772 -0.6973396 ]]
[42.6354442 45.3430349]
[[ 0.56458597 -0.4868121 ]
 [-0.37116888  0.10191183]]
[-1.76563854e-02  1.00766584e+02]
[[ 1.03270342 -0.87513547]
 [ 0.03510869 -0.02932828]]
[ 56.52220916 -82.49387778]
[[ 1.47414123 -0.69200672]
 [ 1.01003518 -0.47414123]]
[99.68314039  7.95433978]
[[-0.04031233 -0.08301301]
 [ 0.50519085  1.04031233]]
[-42.03241539 -22.13034698]
[[-1.74119556 -0.67823393]
 [ 3.30707219  1.28817728]]
[41.55752009 37.50712134]
[[ 0.38005366 -0.50693416]
 [-0.37226222  0.32424631]]
[ 17.0485683  101.80231049]
[[ 0.74565266 -1.23041775]
 [-0.17854665  0.28156255]]
[ 43.15511865 -90.2088451 ]
[[ 1.34442601 -0.71996726]
 [ 0.643

[ 31.91939433 120.77530153]
[[ 0.37822644 -1.51288239]
 [-0.21350287  0.6297591 ]]
[ 38.06308357 -92.4727077 ]
[[ 1.2660741  -0.64641617]
 [ 0.52113413 -0.2660741 ]]
[ 99.16602675 -12.88794547]
[[0.09130729 0.11809672]
 [0.702562   0.90869271]]
[-29.77800265   7.24139837]
[[ 0.34601922 -0.14443926]
 [ 1.42289663 -0.59396161]]
[51.0946742  48.33875106]
[[ 0.23874941 -0.55045163]
 [-0.24610296  0.62399489]]
[ 31.00857834 125.0753351 ]
[[ 0.38859246 -1.53176518]
 [-0.21472424  0.61074856]]
[ 36.80115031 -92.98212374]
[[ 1.25777092 -0.65128636]
 [ 0.49780984 -0.25777092]]
[ 98.96993978 -14.31611052]
[[0.1049476  0.12947031]
 [0.72552232 0.8950524 ]]
[-28.87116508   7.80363376]
[[ 0.37162325 -0.16589481]
 [ 1.37489744 -0.61376232]]
[52.38034133 48.32530689]
[[ 0.22557747 -0.55663967]
 [-0.23837635  0.64012552]]
[ 31.77173318 125.72155077]
[[ 0.38697029 -1.53259654]
 [-0.21280853  0.61173036]]
[ 36.1909943  -93.22130621]
[[ 1.24507776 -0.63127497]
 [ 0.48337235 -0.24507776]]
[ 98.83676502 -1

[ 45.28093484 -89.16073654]
[[ 1.13754145 -0.27082694]
 [ 0.57770878 -0.13754145]]
[99.8547389  -5.38805336]
[[0.03419012 0.05211405]
 [0.63363252 0.96580988]]
[-15.0741106    5.29244362]
[[ 0.35764095 -0.18312998]
 [ 1.01864463 -0.52159679]]
[51.48309148 67.2575897 ]
[[ 0.3499114  -0.70348762]
 [-0.26367691  0.58599388]]
[  2.1274679  143.15261349]
[[ 0.84539662 -1.46427557]
 [-0.12280243  0.13911208]]
[ 36.93073232 -92.93073232]
[[ 1.18754587 -0.47193149]
 [ 0.47193149 -0.18754587]]
[ 98.96993978 -14.31611052]
[[0.1049476  0.12947031]
 [0.72552232 0.8950524 ]]
[-19.3100311    7.74149858]
[[ 0.42134109 -0.24315024]
 [ 1.05097346 -0.60650256]]
[55.78538663 57.53633951]
[[ 0.25005785 -0.63168429]
 [-0.23332137  0.66330947]]
[ 21.79112469 137.43322134]
[[ 0.57098412 -1.56470221]
 [-0.20299918  0.4145443 ]]
[ 38.57771564 -92.2591993 ]
[[ 1.18701837 -0.44725731]
 [ 0.4963457  -0.18701837]]
[ 99.16602675 -12.88794547]
[[0.09130729 0.11809672]
 [0.702562   0.90869271]]
[-19.43185185   7.3950

[ 63.9964683  -76.84043235]
[[ 1.00704912 -0.00846387]
 [ 0.83871974 -0.00704912]]
[98.45627024 17.50322401]
[[-0.07228557 -0.19062732]
 [ 0.40660894  1.07228557]]
[-15.80200783   1.80546816]
[[ 0.13329205 -0.03393088]
 [ 1.16661265 -0.29697343]]
[35.60643893 77.56190099]
[[ 0.57728966 -0.7086078 ]
 [-0.26991577  0.35989844]]
[-30.56668598 139.88934404]
[[ 1.16524122 -1.20593073]
 [ 0.1258063  -0.17876245]]
[ 70.96755524 -70.45286441]
[[0.97497648 0.02484203]
 [0.98209914 0.02502352]]
[96.44102864 26.44102864]
[[-0.08127747 -0.29645151]
 [ 0.29645151  1.08127747]]
[-21.43630629  -0.78438723]
[[-0.04805134  0.00513648]
 [ 1.31318201 -0.14037356]]
[28.54902586 74.33685136]
[[ 0.61820634 -0.64166638]
 [-0.24851363  0.29634487]]
[-33.19305612 135.50279614]
[[ 1.17257742 -1.270386  ]
 [ 0.10514777 -0.19062383]]
[ 80.97001166 -58.68438644]
[[0.83362799 0.12058093]
 [1.15020148 0.16637201]]
[91.0324338  41.38956386]
[[-0.05315157 -0.47883466]
 [ 0.11690186  1.05315157]]
[-24.15449184  -5.6809

[84.21249339 53.92824823]
[[ 0.0236968  -0.62520796]
 [-0.0370041   0.9763032 ]]
[-24.50795765 -10.24453209]
[[-0.54320049 -0.13583023]
 [ 1.29949659  0.32494618]]
[ 7.47416278 73.93413363]
[[ 0.80774795 -0.44471788]
 [-0.10048984  0.07724237]]
[-62.15635761 118.24986123]
[[ 1.36748731 -0.89818744]
 [ 0.4641816  -0.37702092]]
[ 89.11014017 -45.3804244 ]
[[0.63926553 0.18370843]
 [1.25527783 0.36073447]]
[83.61194664 54.8547389 ]
[[ 0.03419012 -0.63363252]
 [-0.05211405  0.96580988]]
[-24.43994768 -10.66392346]
[[-0.56219777 -0.14977888]
 [ 1.28846425  0.34326841]]
[ 6.22109353 74.10335589]
[[ 0.81468543 -0.43890824]
 [-0.0891596   0.07156432]]
[-64.40091129 117.39537824]
[[ 1.36693551 -0.85631969]
 [ 0.49034104 -0.37707018]]
[ 90.34964157 -42.85956449]
[[0.6001103  0.18969747]
 [1.26505603 0.3998897 ]]
[81.70587375 57.65544375]
[[ 0.05547172 -0.66650284]
 [-0.07861123  0.94452828]]
[-24.25336311 -11.47030401]
[[-0.59790426 -0.17871611]
 [ 1.26423756  0.37788595]]
[ 3.65861365 73.883865

[99.77520134 -6.70143243]
[[0.08160822 0.06168407]
 [1.21503531 0.91839178]]
[54.75323932 83.67844874]
[[ 0.42988916 -0.87129074]
 [-0.28128896  0.57011084]]
[-19.4967629  -22.90413394]
[[-0.90466473 -0.7767515 ]
 [ 0.7700808   0.66119679]]
[-21.86247928  67.71391013]
[[ 0.87023109 -0.06870058]
 [ 0.25212554 -0.002129  ]]
[-99.55193894  83.45139205]
[[ 1.26920968 -0.22078742]
 [ 1.12066981 -0.27222538]]
[99.79079428 -6.46508911]
[[0.08433247 0.05932283]
 [1.30169967 0.91566753]]
[54.75323932 83.67844874]
[[ 0.42988916 -0.87129074]
 [-0.28128896  0.57011084]]
[-20.11015167 -26.81353556]
[[-0.98341024 -0.9478747 ]
 [ 0.73755768  0.71090603]]
[-18.86083596  64.58561625]
[[ 0.84872415 -0.05742231]
 [ 0.22895781 -0.00394198]]
[-92.85678813  83.79881674]
[[ 1.2893159  -0.26308542]
 [ 1.04267971 -0.28294502]]
[99.7935113  -6.42301343]
[[0.08993143 0.05857478]
 [1.39725269 0.91006857]]
[54.75323932 83.67844874]
[[ 0.42988916 -0.87129074]
 [-0.28128896  0.57011084]]
[-20.0036385  -31.05096498]


[ 39.64380565 -91.80614726]
[[ 1.39458941 -0.91378043]
 [ 0.60221274 -0.39458941]]
[ 99.36254355 -11.27319562]
[[0.07910394 0.10448043]
 [0.69722634 0.92089606]]
[-42.44607636  -2.34621393]
[[-0.13330305  0.01333815]
 [ 2.41162642 -0.24130465]]
[46.75385673 34.99452309]
[[ 0.21689485 -0.48288036]
 [-0.29579718  0.55085626]]
[ 37.20373903 104.85614167]
[[ 0.34434858 -1.38071038]
 [-0.20222603  0.68556065]]
[ 28.94459801 -95.71943505]
[[ 1.28100348 -0.92927512]
 [ 0.38736262 -0.28100348]]
[ 97.33357078 -22.93852651]
[[0.1848366  0.19210892]
 [0.78430522 0.8151634 ]]
[-35.21675051   8.29268203]
[[ 0.39124266 -0.16239777]
 [ 1.66150048 -0.68965887]]
[52.73619596 36.4330877 ]
[[ 0.14834171 -0.46389047]
 [-0.21452261  0.67234896]]
[ 46.94549351 111.01931721]
[[ 0.15856729 -1.41632136]
 [-0.15010566  0.85696486]]
[ 23.92875626 -97.09487434]
[[ 1.22743462 -0.92285346]
 [ 0.30249778 -0.22743462]]
[ 95.85312524 -28.4987435 ]
[[0.24024008 0.22588938]
 [0.80802729 0.75975992]]
[-30.89920526  11.24

[[ 0.08557158 -0.48651167]
 [-0.10174453  0.82338325]]
[ 53.96737753 127.20427221]
[[ 0.13505554 -1.49503958]
 [-0.13446676  0.85035346]]
[ 14.93087743 -98.87906199]
[[ 1.11326984 -0.7501244 ]
 [ 0.16810531 -0.11326984]]
[ 93.01744009 -36.71179427]
[[0.33724231 0.26157486]
 [0.85447788 0.66275769]]
[-15.87306293  11.40414858]
[[ 0.53995535 -0.51661696]
 [ 0.75154626 -0.71906232]]
[68.52593669 44.9612115 ]
[[ 0.08360698 -0.50495854]
 [-0.09652693  0.84061663]]
[ 52.22209137 130.98266734]
[[ 0.19047871 -1.51764748]
 [-0.15061402  0.79288728]]
[ 14.5596234  -98.93440942]
[[ 1.10711314 -0.72784683]
 [ 0.16292765 -0.10711314]]
[ 93.01744009 -36.71179427]
[[0.33724231 0.26157486]
 [0.85447788 0.66275769]]
[-14.56238951  10.85802753]
[[ 0.53306015 -0.52638341]
 [ 0.71492078 -0.70596618]]
[69.32533808 46.12728003]
[[ 0.08537254 -0.51973985]
 [-0.10141827  0.84367123]]
[ 49.09036478 133.14172923]
[[ 0.26040694 -1.5085531 ]
 [-0.16907867  0.7246696 ]]
[ 14.86946473 -98.88831589]
[[ 1.1033924  -0

In [ ]:
result

In [ ]:
# dynamics simulation 

def get_force(angle, mass): return mass * -9.81 * np.sin(angle)
# game loop implementation

# system parameters
pendulum_mass = 0.7  #kg
pendulum_string_length = 0.1 #m

# step
dt = 0.01

# system state (incl. initial conditions)
pendulum_angle = 1.2
pendulum_angular_velocity = 0

result = []

# step between 0s and 10s every dt seconds
for step in np.arange(0.0, 100.0, dt):
    # get acceleration
    # F = m*a  ->  a = F/m
    
    # TODO implement update call
    
    result.append(pendulum_angle)
    
plt.plot(result)
plt.show()

In [ ]:
# dynamics simulation 

def get_force(angle, mass): return mass * -9.81 * np.sin(angle)
# game loop implementation

# system parameters
pendulum_mass = 0.7  #kg
pendulum_string_length = 0.1 #m

# step
dt = 0.01

# system state (incl. initial conditions)
pendulum_angle = 1.2
pendulum_angular_velocity = 0

result = []

# step between 0s and 10s every dt seconds
for step in np.arange(0.0, 100.0, dt):
    # get acceleration
    # F = m*a  ->  a = F/m
    acceleration = get_force(pendulum_angle, pendulum_mass) / pendulum_mass
    
    # do the time step
    pendulum_angle += pendulum_angular_velocity * dt
    pendulum_angular_velocity += acceleration * dt
    result.append(pendulum_angle)
    
plt.plot(result)
plt.show()

In [ ]:
import matplotlib.pyplot as plt

# is an approximation since time is discretized

# let's be a little smarter about discretization

# battle plan formulate system as a continuous-time model -> pass it to a differential equation solver

# function that returns dy/dt
# variable naming convention from control theory:
# y -> system state vector (sometimes 'u')
# t -> time
# p -> parameter vector
def model(t, y, p=()):
    pendulum_angle = y[0]
    pendulum_anglular_velocity = y[1]
    
    # TODO implement model

# initial condition
y0 = [0,10]

from scipy.integrate import solve_ivp

# time points
time_span = (0.0, 100.0)

# solve ODEs
k = 0.1
result = solve_ivp(model, time_span, y0, method='RK45', rtol=1e-8)

fig = plt.figure()
ax = fig.add_subplot(1, 2, 2)
ax.plot(result.y[0, :],
        result.y[1, :])
ax.set_title("solve_ivp")
result
# time plot

In [ ]:
# @Lukas TODO put it on the repo in seperate file
import matplotlib.pyplot as plt

# is an approximation since time is discretized

# let's be a little smarter about discretization

# battle plan formulate system as a continuous-time model -> pass it to a differential equation solver

# function that returns dy/dt
# variable naming convention from control theory:
# y -> system state vector (sometimes 'u')
# t -> time
# p -> parameter vector
def model(t, y, p=()):
    pendulum_angle = y[0]
    pendulum_anglular_velocity = y[1]
    
    acceleration = get_force(pendulum_angle, pendulum_mass) / pendulum_mass
    
    return [pendulum_angular_velocity, acceleration]

# initial condition
y0 = [0,10]

from scipy.integrate import solve_ivp


# time points
time_span = (0.0, 100.0)

# solve ODEs
k = 0.1
result = solve_ivp(model, time_span, y0, method='RK45', rtol=1e-8)

fig = plt.figure()
ax = fig.add_subplot(1, 2, 2)
ax.plot(result.y[0, :],
        result.y[1, :])
ax.set_title("solve_ivp")
result
# time plot

In [ ]:
# TODO state-space-plot


In [ ]:
# TODO make this work for the linkage system


In [ ]:
# TODO run FFT on the data
